Lets get started with some basic NumPy challenges:

How to import NumPy library?

In [1]:
import numpy as np

How to know its version?

In [2]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Lenovo/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Lenovo/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib

    How to create a null vector of size 20?

In [3]:
A=np.zeros(20)

In [4]:
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


How to find the memory size of any array?

In [5]:
B = np.zeros((10,10))
print("%d bytes" % (B.size * B.itemsize))

800 bytes


How to find common elements from 2 arrays?

In [6]:
Z1 = np.random.randint(0,20,60)
Z2 = np.random.randint(0,60,20)
print(np.intersect1d(Z1,Z2))

[ 1  2  5  7  9 14 18 19]


How to join two arrays?

In [8]:
Z1= np.array([1, 2, 3])
Z2 = np.array([4, 5, 6])
Z = np.concatenate((Z1,Z2))
print(Z)

[1 2 3 4 5 6]


How to find the type of object passed to above array?

In [9]:
print(type(Z))

<class 'numpy.ndarray'>


How to change data type from float to integer by using 'i' as parameter value?

In [10]:
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
